package main

const (
	SPRITE_SCALE_FACTOR      = 3.0
	TILE_SIZE_IN_PIXELS      = 16*SPRITE_SCALE_FACTOR
	TILE_SIZE_TRUE           = 16
	PIXEL_TO_GAMECOORD_RATIO = TILE_SIZE_IN_PIXELS/TILE_SIZE_TRUE

	MAP_SIZE = 13
)
