package main

const (
	SPRITE_SCALE_FACTOR      = 4.0
	TILE_SIZE_IN_PIXELS      = 16*SPRITE_SCALE_FACTOR
	TILE_SIZE_TRUE           = 16
	PIXEL_TO_GAMECOORD_RATIO = TILE_SIZE_IN_PIXELS/TILE_SIZE_TRUE

	MAP_W = 20
	MAP_H = 15
	NUM_FACTIONS = 4
)
